### ISSUE TITLE
Hacktoberfest2020

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#1]
## What is Hacktoberfest?

**Hacktoberfest is open to everyone in our global community. Whether you’re new to development, a student, long-time contributor, event host, or company of any size, you can help drive growth of open source and make positive contributions to an ever-growing community. All backgrounds and skills levels are encouraged to complete the challenge.**

## When can I start contributing?

**Your contribution will be counted in Hacktoberfest from 1st October to 31 October but you can start contributing to this repo whenever you like as it will help you in getting a taste of Open-Source-Development.**

## What will I get?

**Apart from Open Source experience  you can also win a free T-shirt from Hacktoberfest if you make 4 successful PRs during the month of October.**

**To know more about the swags and guidelines please visit [here](https://hacktoberfest.digitalocean.com/)**

**Comment by AdityaJ7** [comment]
We will start posting issues from this weekend, interested people can claim them by commenting on an issue of their choice.
Issues will be assigned on a first-come-first-serve basis.

Thanks

**Comment by TEMHITHORPHE** [comment]
can i post an issue and request to be assigned to it?

**Comment by AdityaJ7** [comment]
> can i post an issue and request to be assigned to it?

Yes sure @TEMHITHORPHE just make sure the script that you want to work on is not already present either in this repo or in our sister repo called python-mini-projects
