### ISSUE TITLE
How to push a installation package from server without any tool and to process it with all installation automation 

### ISSUE THREAD

**Issue by girishkulkarni832** [Python-World/Python_and_the_Web#100]
# Description

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [ ] I have read the project guidelines.
- [ ] I have checked all the existing projects, before submitting a new project issue.
- [ ] I have checked previous issues to avoid duplicates.
- [ ] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Hi @girishkulkarni832 please drop such kind of queries in our WhatsApp group
