### ISSUE TITLE
Michelin star restaurants scraper 

### ISSUE THREAD

**Issue by killerpanda101** [Python-World/Python_and_the_Web#114]
# Description

website to scraper https://guide.michelin.com/en/restaurants

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by killerpanda101** [comment]
please assign this to me,

**Comment by officialpm** [comment]
#### I would like to do it🤘🏻

**Comment by AdityaJ7** [comment]
> please assign this to me,

sure @killerpanda101

**Comment by killerpanda101** [comment]
can you reopen this thread
