### ISSUE TITLE
Social Media Scanner

### ISSUE THREAD

**Issue by madhavmehndiratta** [Python-World/Python_and_the_Web#115]
# Description

Open-source intelligence (OSINT) is data collected from publicly available sources to be used in an intelligence context. OSINT has been used by hackers for the Information Gathering process. The Information comes from variety of sources including social media pages, personal blogs, websites etc 

This scripts check if a username is present on social media websites or not. For example if you supply any username (say shawnmendes) it which look for it on Twitter, Instagram and Facebook and tell if the username is available or not.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by madhavmehndiratta** [comment]
I would like to be assigned for this project

**Comment by TEMHITHORPHE** [comment]
i would love to be assigned too ... is that possible

**Comment by AdityaJ7** [comment]
> I would like to be assigned for this project

Sure @madhavmehndiratta you are assigned

**Comment by AdityaJ7** [comment]
> i would love to be assigned too ... is that possible

Sorry but he claimed the issue before you
