### ISSUE TITLE
Pong game with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#123]
# Description

Create  a pong game with python

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Vyprath** [comment]
Hey, I'd love to do this project!

**Comment by AdityaJ7** [comment]
> Hey, I'd love to do this project!

Sure go for it @Vyprath

**Comment by Vyprath** [comment]
I've opened a PR.
