### ISSUE TITLE
Sudoku game with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#124]
# Description

Create a GUI based sudoku game with Python

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by ankitsridhar16** [comment]
I will work on this . Can you assign it to me ?

**Comment by AdityaJ7** [comment]
> I will work on this . Can you assign it to me ?

sure @ankitsridhar16
