### ISSUE TITLE
Connect 4 (C4) game with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#125]
# Description

Create a GUI based Connect 4 game with Python

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by SuvamPrasd** [comment]
@AdityaJ7 I want to work on this issue

**Comment by AdityaJ7** [comment]
> @AdityaJ7 I want to work on this issue

sure @SuvamPrasd

**Comment by SuvamPrasd** [comment]
Thanks, @AdityaJ7
