### ISSUE TITLE
Classic Snake game with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#126]
# Description

Create the classic snake game with python

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by infern018** [comment]
@AdityaJ7  can I work on this?

**Comment by AdityaJ7** [comment]
> @AdityaJ7 can I work on this?

Sure @infern018
