### ISSUE TITLE
Spotify Playlist Generator

### ISSUE THREAD

**Issue by sandyjswl** [Python-World/Python_and_the_Web#134]
# Generate multiple playlists of a given size from a large Spotify playlist.

This script will generate multiple smaller spotify playlist from a large spotify playlist and shuffle them and add them to your spotify account
## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
cool @sandyjswl  go for it, add your script under Miscellaneous

**Comment by sandyjswl** [comment]
Sure thanks.
