### ISSUE TITLE
Mad Libs Generator

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#135]
# Description

Create a mad libs generator with python.

Check this link to know more about Mad libs -- [Mad libs](https://en.wikipedia.org/wiki/Mad_Libs)

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Jayanth19524** [comment]
I want to work on this.

**Comment by AdityaJ7** [comment]
> I want to work on this.

Sure @Jayanth19524

**Comment by Jayanth19524** [comment]
> > I want to work on this.
> 
> Sure @Jayanth19524
can u please help me with an error called deepsource error?@AdityaJ7
