### ISSUE TITLE
Scrape/extract emails from text files

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#138]
# Description

write a script that extracts email addresses, if any from a given file.
Do keep a count of multiple entries for the same email

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by aswarth123** [comment]
I want to work on this issue can you assign it to me?

**Comment by aswarth123** [comment]
I also wanted to know that where I need to add this script?

**Comment by AdityaJ7** [comment]
> I also wanted to know that where I need to add this script?

Sure you can work on it add it under Miscellaneous

**Comment by Jayanth19524** [comment]
please I want to work on this

**Comment by AdityaJ7** [comment]
> please I want to work on this

This issue has been claimed already @Jayanth19524

**Comment by aswarth123** [comment]
#149
