### ISSUE TITLE
Scrape News from JustDial.com

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#14]
# Description

Create a script that scrapes news from the justdial.com as per the user request.
For example, The user might request only cricket news or only tech news.

Here is the link for reference: [Link](https://www.justdial.com/JdSocial/news-latest)

## Type of issue
- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by grplyler** [comment]
If this is still available, I'd like to take a crack at this issue for Hacktoberfest 2020. Thanks!

**Comment by AdityaJ7** [comment]
> If this is still available, I'd like to take a crack at this issue for Hacktoberfest 2020. Thanks!

Sure, this is available.
