### ISSUE TITLE
Telegram Chatbot for detecting skin ailments

### ISSUE THREAD

**Issue by RitikaAg** [Python-World/Python_and_the_Web#141]
# Description

A telegram chatbot that will allow the user to take a selfie and gives them an approximate run down of visible skin ailments like acne through image detection

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [ X] I have checked all the existing projects, before submitting a new project issue.
- [ X] I have checked previous issues to avoid duplicates.
- [ X] This issue will be meaningful for the project.

**Comment by MontyGhost** [comment]
I would like to work on this, please assign this to me
Thank you!

**Comment by AdityaJ7** [comment]
> I would like to work on this, please assign this to me
> Thank you!

This issue has been claimed
