### ISSUE TITLE
IMDb_Scrapper

### ISSUE THREAD

**Issue by dvlp-jrs** [Python-World/Python_and_the_Web#142]
# Description

Write a script to scrap data from IMDb.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
What are u going to scrape ?

**Comment by dvlp-jrs** [comment]
> What are u going to scrape ? @dvlp-jrs

The following data
    final_data = {
        'imdb_id' : imdb_id,
        'names' : {
            'p_title' : p_title,
            'o_title' : p_title
        },
        'run_time' : run_time,
        'genres' : genres,
        'rating' : {
            'imdb_rating' : imdb_rating,
            'metascore' : metascore
        },
        'description' : {
            'plot' : imdb_plot_1,
            'summary' : imdb_plot_2
        },
        'production' : production,
        'cast' : cast,
        'keywoards' : keywoards,
        'basic_info' : {
            'country' : country,
            'language' : language,
            'release_date' : {
                'day' : release_day,
                'month' : release_month,
                'year' : release_year
            },
            'country' : country
        },
        'media' : {
            'posted' : poster,
            'trailer' : trailer
        },
        'review' : review
    }

**Comment by AdityaJ7** [comment]
> > What are u going to scrape ? @dvlp-jrs
> 
> The following data
> final_data = {
> 'imdb_id' : imdb_id,
> 'names' : {
> 'p_title' : p_title,
> 'o_title' : p_title
> },
> 'run_time' : run_time,
> 'genres' : genres,
> 'rating' : {
> 'imdb_rating' : imdb_rating,
> 'metascore' : metascore
> },
> 'description' : {
> 'plot' : imdb_plot_1,
> 'summary' : imdb_plot_2
> },
> 'production' : production,
> 'cast' : cast,
> 'keywoards' : keywoards,
> 'basic_info' : {
> 'country' : country,
> 'language' : language,
> 'release_date' : {
> 'day' : release_day,
> 'month' : release_month,
> 'year' : release_year
> },
> 'country' : country
> },
> 'media' : {
> 'posted' : poster,
> 'trailer' : trailer
> },
> 'review' : review
> }

A similar kind of script is present in our sister repo -- python-mini-projects

**Comment by AdityaJ7** [comment]
You can try A similar kind of script with Rotten-tomatoes if you want
