### ISSUE TITLE
Scrape Top 100 movies as per genre entered by the user

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#144]
# Description

Scrape the top 100 movies from Rotten-Tomatoes as per the genre entered by the user.
Store the result in a CSV file

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Anshul275** [comment]
Ready to work on it. Please Assign it to me.

**Comment by AdityaJ7** [comment]
> Ready to work on it. Please Assign it to me.

Sure @Anshul275

**Comment by piotrrybinski88** [comment]
Hi, can i work on this also ?

**Comment by AdityaJ7** [comment]
> Hi, can i work on this also ?

Sorry this issue has already been claimed

**Comment by Anshul275** [comment]
Should i attach one of the generated csv files too. Screenshots are needed or not??

**Comment by AdityaJ7** [comment]
> Should i attach one of the generated csv files too. Screenshots are needed or not??

nope
