### ISSUE TITLE
Scrape movie information from Rotten Tomatoes

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#145]
# Description

Scrape Critics Consensus, TOMATOMETER and Audience score for a movie as requested by the user.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Jaideep07** [comment]
I would like to try this can you assign this to me.

**Comment by AdityaJ7** [comment]
> I would like to try this can you assign this to me.

Sure @Jaideep07

**Comment by Jaideep07** [comment]
@AdityaJ7 should I add a demo of it also as a readme ??

**Comment by AdityaJ7** [comment]
> @AdityaJ7 should I add a demo of it also as a readme ??

Add a screenshot for demo
