### ISSUE TITLE
Voice Enabled Chatbot for stackoverflow questions

### ISSUE THREAD

**Issue by RitikaAg** [Python-World/Python_and_the_Web#148]
# Description

A telegram chatbot that will take in technical voice queries and give answers by scraping stackoverflow

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by RitikaAg** [comment]
Please assign this to me

**Comment by AdityaJ7** [comment]
> Please assign this to me

Cool @RitikaAg assigned to you

**Comment by MontyGhost** [comment]
I would also like to contribute to this project. Thank you!

**Comment by AdityaJ7** [comment]
> I would also like to contribute to this project. Thank you!

This issue has been claimed already
