### ISSUE TITLE
covid data visualization using streamlit

### ISSUE THREAD

**Issue by chavarera** [Python-World/Python_and_the_Web#15]
**Problem Statement**
Create sample COVID-19 data visualization using stream lit

stream lit
https://www.streamlit.io/
`
Streamlit’s open-source app framework is the easiest way for data scientists and machine learning engineers to create beautiful, performant apps in only a few hours!  All in pure Python. All for free.
`

**Comment by Aravindha1234u** [comment]
Hey, I can help in making this one, Since I have already deployed one with Django and willing to learn something new from streamlit. 

https://covidin.herokuapp.com/

**Comment by AdityaJ7** [comment]
> Hey, I can help in making this one, Since I have already deployed one with Django and willing to learn something new from streamlit.
> 
> https://covidin.herokuapp.com/

Sure go ahead with it

**Comment by Aravindha1234u** [comment]
Do this has any requirements I have planned to active, recovered and dead is there other ?

**Comment by AdityaJ7** [comment]
> Do this has any requirements I have planned to active, recovered and dead is there other ?

These three are enough

**Comment by Aravindha1234u** [comment]
Hey Bro. I am done with app with streamlit. Should I need to deploy using heroku and give you or how should I need to complete this issue bro ?

![image](https://user-images.githubusercontent.com/52521300/94795192-a92df200-03fa-11eb-8ef7-00af74ea962d.png)

**Comment by AdityaJ7** [comment]
> Hey Bro. I am done with app with streamlit. Should I need to deploy using heroku and give you or how should I need to complete this issue bro ?
> 
> ![image](https://user-images.githubusercontent.com/52521300/94795192-a92df200-03fa-11eb-8ef7-00af74ea962d.png)

You can deploy for your personal use, it will be a good addition while here u just need to submit source code.

**Comment by Aravindha1234u** [comment]
Ok, Then I will create a Repository and give you the link here bro.

**Comment by AdityaJ7** [comment]
> Ok, Then I will create a Repository and give you the link here bro.

Make a PR to this repo

**Comment by Aravindha1234u** [comment]
Done Bro 

https://github.com/Python-World/Python_and_the_Web/pull/88
