### ISSUE TITLE
Google maps API

### ISSUE THREAD

**Issue by Mysterious-Owl** [Python-World/Python_and_the_Web#155]
# Description

You enter the address and it will mark its coordinate on maps on website, according to google maps, will use google maps api to get coordinates and map

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by Jayanth19524** [comment]
even though this has been assigned to someone else can I work on this and make a pull request?

**Comment by Mysterious-Owl** [comment]
> even though this has been assigned to someone else can I work on this and make a pull request?

I made a pr already, if possible provide feedback.
