### ISSUE TITLE
Create basic music player

### ISSUE THREAD

**Issue by chavarera** [Python-World/Python_and_the_Web#16]
**Problem statement**
Create basic music player

**Comment by Priyam145** [comment]
Hey I would like to work on this. Can you assign this to me?

**Comment by AdityaJ7** [comment]
> Hey I would like to work on this. Can you assign this to me?

Sure!!

**Comment by ritesh-dt** [comment]
Can I work on this? I'll make a player where the user can select a music file and play it. The GUI would also have play/pause and rewind functionality.

**Comment by AnkDos** [comment]
Any plan for this ? like what lib should be used for interface and what one specific problem shall be solved ? we can use jython for using swing elements of java and will it be a regular music player or any specific feature to go with ? @AdityaJ7

**Comment by ritesh-dt** [comment]
I've tried a few libraries like pydub, simpleaudio, etc. But the libraries only support playing (not pause-ans-play). So I'm stuck currently. @AnkDos What are swing elements?

**Comment by AdityaJ7** [comment]
> Any plan for this ? like what lib should be used for interface and what one specific problem shall be solved ? we can use jython for using swing elements of java and will it be a regular music player or any specific feature to go with ? @AdityaJ7

A regular music player will do the trick

**Comment by ritesh-dt** [comment]
> A regular music player will do the trick

@AdityaJ7 As in just select file and play? Or play and pause functionality?

**Comment by AnkDos** [comment]
@ritesh-dt   java swing provides a way to create window-based applications . So if you want to build the whole interface with all the button functionalities , it'll be useful .These java libraries can be imported in python for developing the ui , so you're code base will be in python

**Comment by AdityaJ7** [comment]
> > A regular music player will do the trick
> 
> @AdityaJ7 As in just select file and play? Or play and pause functionality?

Select, play, pause, exit

**Comment by ritesh-dt** [comment]
> Select, play, pause, exit

Great 👍, I'll get that working but currently **I'm in the middle of my exams 📚**. So I'll work on this as soon as I'm free.

**Comment by AdityaJ7** [comment]
> > Select, play, pause, exit
> 
> Great 👍, I'll get that working but currently **I'm in the middle of my exams 📚**. So I'll work on this as soon as I'm free.

ok no problem, best of luck for the exams
