### ISSUE TITLE
Google search using python

### ISSUE THREAD

**Issue by krishnajalan** [Python-World/Python_and_the_Web#169]
# Description
link in README.md is incorrect for this project.
link for the wifi speed project is duplicated for this project too.
kindly update the correct repo link.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Feature (New Script)
- [ ] Bug
- [ x ] Documentation

## Checklist:

- [ x ] I have read the project guidelines.
- [ x ] I have checked all the existing projects, before submitting a new project issue.
- [ x ] I have checked previous issues to avoid duplicates.
- [ x ] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Ok fix the link for the google search project
