### ISSUE TITLE
Convert JSON to YAML

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#17]
# Description

Create a script that takes a JSON file as input and converts it into a YAML file.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Unassigning due to inactivity

**Comment by mendoza** [comment]
I would love to work on this issue, pls assigned to me

**Comment by AdityaJ7** [comment]
> I would love to work on this issue, pls assigned to me

Sure @mendoza
