### ISSUE TITLE
Face Detection in Python Using a Webcam

### ISSUE THREAD

**Issue by MitanshiKshatriya** [Python-World/Python_and_the_Web#18]
# Description

Write a basic script to detect faces in webcam using haar cascade. 

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [ ] I have checked all the existing projects, before submitting a new project issue.
- [ ] I have checked previous issues to avoid duplicates.
- [ ] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Are you working on it @MitanshiKshatriya

**Comment by MitanshiKshatriya** [comment]
Yes I will make a pr today itself

**Comment by AdityaJ7** [comment]
> Yes I will make a pr today itself

I guess you should make it tomorrow so that it will be counted under Hacktoberfest , if you are participating in it

**Comment by MitanshiKshatriya** [comment]
ok I will make a PR tomorrow then
