### ISSUE TITLE
Upcoming Rocket Launch Schedule | Web Scrapper

### ISSUE THREAD

**Issue by Rajdeep-Ray** [Python-World/Python_and_the_Web#181]
# Description

The script will scrape the Details of the upcoming Rocket Launch Schedule and return in a JSON

## Type of issue

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Rajdeep-Ray** [comment]
I would like to work on this

**Comment by AdityaJ7** [comment]
> I would like to work on this

Sure @Rajdeep-Ray

**Comment by Rajdeep-Ray** [comment]
@AdityaJ7 Could you assign me this Issue
