### ISSUE TITLE
GUI Password Generator

### ISSUE THREAD

**Issue by rockingrohit9639** [Python-World/Python_and_the_Web#184]
# Description

Hi, I am Rohit Kumar Saini. I am new to open source contributions. I have created a GUI based Password generator. It has three types of passwords to be generated i.e. PIN, AlphaNumeric, Extreme Secure. 
So I want to start my contribution by adding this project of mine to your repo.
So can I add my project to it?
Thank you.

**Comment by AdityaJ7** [comment]
Place it under Miscellaneous directory  @rockingrohit9639

**Comment by rockingrohit9639** [comment]
Ok sir, Thank you very much for helping me.

**Comment by AdityaJ7** [comment]
> Ok sir, Thank you very much for helping me.

No problem @rockingrohit9639  and you don't have to call me sir.

**Comment by rockingrohit9639** [comment]
> > Ok sir, Thank you very much for helping me.
> 
> No problem @rockingrohit9639 and you don't have to call me sir.

May I get your number or any contact detail so that you can help me further if you don't mind?

**Comment by AdityaJ7** [comment]
> > > Ok sir, Thank you very much for helping me.
> > 
> > 
> > No problem @rockingrohit9639 and you don't have to call me sir.
> 
> May I get your number or any contact detail so that you can help me further if you don't mind?

Join our whatsapp group #40
