### ISSUE TITLE
GUI-based Tic Tac Toe Game using Python

### ISSUE THREAD

**Issue by madhavmehndiratta** [Python-World/Python_and_the_Web#186]
# Description
I would like to create a tic tac toe game using `tkinter` library in python.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by madhavmehndiratta** [comment]
Please assign me this project

**Comment by AdityaJ7** [comment]
> Please assign me this project

Sure @madhavmehndiratta

**Comment by Swatichanchal** [comment]
I would like to work on this , please assign me this project .

**Comment by AdityaJ7** [comment]
> I would like to work on this , please assign me this project .

Sorry @Swatichanchal but this issue has been taken already

**Comment by Swatichanchal** [comment]
okay no problem .

**Comment by Swatichanchal** [comment]
also I can change the UI of the game , like playing tic tac toe in canvas . If you want me to do that .

**Comment by AdityaJ7** [comment]
> also I can change the UI of the game , like playing tic tac toe in canvas . If you want me to do that .

To change something it needs to created  first, correct me if I am wrong @Swatichanchal

**Comment by Swatichanchal** [comment]
then let me create a different type of tic tac toe game , the concept will be same but the UI and method will be different

**Comment by AdityaJ7** [comment]
> then let me create a different type of tic tac toe game , the concept will be same but the UI and method will be different

Having the same thing in different flavours won't be a meaningful contribution - we already have two command line tic tac toes and one GUI based is under progress so I don't think we want another Tic Tac toe because in the end all four of them will have the same functionality. Hope you understand

Thanks
