### ISSUE TITLE
Zoom Scraper

### ISSUE THREAD

**Issue by nmreddy1911** [Python-World/Python_and_the_Web#189]
# Description

A Python Web Scraper to extract the participants from an ongoing zoom call.

## Type of issue

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by Anshul275** [comment]
I am ready for this. Please assign the task to me :)

**Comment by AdityaJ7** [comment]
> I am ready for this. Please assign the task to me :)

it has been claimed by the creator !!

**Comment by nmreddy1911** [comment]
Thank you Aditya 😃

**Comment by nmreddy1911** [comment]
> > I am ready for this. Please assign the task to me :)
> 
> it has been claimed by the creator !!

Thank you @AdityaJ7 😃
