### ISSUE TITLE
Convert HTML to Markdown

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#19]
# Description

Write a script to convert an HTML file into a Markdown file.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Unassigning due to inactivity

**Comment by WisnuDS** [comment]
Hi, may I work on this issue?

**Comment by AdityaJ7** [comment]
> Hi, may I work on this issue?

Sure @WisnuDS assigning it to you

**Comment by AdeshChoudhar19** [comment]
This issue is marked stale. Can I work on this, if @WisnuDS agrees?

**Comment by AdityaJ7** [comment]
> This issue is marked stale. Can I work on this, if @WisnuDS agrees?

We'll wait for a day or two and will assign it to you if the concerned person doesn't respond

**Comment by AdeshChoudhar19** [comment]
@AdityaJ7 Are you going to re-open this issue? I would like to work on this.

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Are you going to re-open this issue? I would like to work on this.

Sure you can work on it
