### ISSUE TITLE
Automate Gmail opening and send mail process using selenium library

### ISSUE THREAD

**Issue by hardik-dadhich** [Python-World/Python_and_the_Web#192]
# Description
A python script which helps you to automate sending mail functionality using selenium library.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by hardik-dadhich** [comment]
@AdityaJ7 Can you assign it to me?

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Can you assign it to me?

sure

**Comment by hardik-dadhich** [comment]
@AdityaJ7 can I close it ?
