### ISSUE TITLE
Scapring any new thread in kaskus.com

### ISSUE THREAD

**Issue by k1m0ch1** [Python-World/Python_and_the_Web#197]
# Description

I just made a scraper that scrap any new thread scraper for kaskus.com (a very famous forum in Indonesia) and I want to share it in here, it will be good for indonesia fellow to archive some thread.
this scaper function mostly :
1. scap any new thread into `SingleFileZ` format file
2. check everyday if the thread is deleted, mark the file as `archived`

This will help some of indonesian user in kaskus that his thread can be traced or archived

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ X ] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [ X ] I have read the project guidelines.
- [ X ] I have checked all the existing projects, before submitting a new project issue.
- [ X ] I have checked previous issues to avoid duplicates.
- [ X ] This issue will be meaningful for the project.

I hope this meaningful, @AdityaJ7 can you please assign me this?

**Comment by k1m0ch1** [comment]
I hope this meaningful, @AdityaJ7 can you please assign me this?

**Comment by AdityaJ7** [comment]
> I hope this meaningful, @AdityaJ7 can you please assign me this?

Sure go ahead with it @k1m0ch1
