### ISSUE TITLE
Convert XML to CSV

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#20]
# Description

Write a script that takes an XML file as input and converts it into a CSV file.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by prashanttholia** [comment]
Hi @chavarera, I won't be able to contribute towards this task. I apologize for the inconvenience. Thanks.

**Comment by mendoza** [comment]
I would love to work on this issue too please assigned it to me

**Comment by mendoza** [comment]
Awesome, could you help me too with #17
