### ISSUE TITLE
Image Steganography using Python

### ISSUE THREAD

**Issue by madhavmehndiratta** [Python-World/Python_and_the_Web#200]
# Description

I will be creating a script in which we can hide text inside an image.
Also we can decrypt the text using the same script only

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by madhavmehndiratta** [comment]
Can you assign this project to me?

**Comment by apoorva-dave** [comment]
Can this issue be assigned to me?

**Comment by AdityaJ7** [comment]
> Can this issue be assigned to me?

sorry but the issue creator claimed it first, more issues will be posted soon you can ask to be assigned to them or you can create you brown issue if you feel that some script is missing
