### ISSUE TITLE
Video Steganography using Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#205]
# Description

Perform steganography on a video provided by the user using python

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by matanthings** [comment]
Hey @AdityaJ7, can you assign me to this issue?

**Comment by AdityaJ7** [comment]
> Hey @AdityaJ7, can you assign me to this issue?

sure
