### ISSUE TITLE
Amazon Product Web Scraper

### ISSUE THREAD

**Issue by CaptainRoberts** [Python-World/Python_and_the_Web#210]
# Description

I have an Amazon Web Scraper that gets all the a product has based on the item search URL provided that I wish to share in your repo.
This is my first time contributing to an open-source project and I'm very much looking forward to it! Thanks.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by CaptainRoberts** [comment]
Can you @AdityaJ7 assign this issue to me? Thank you very much, and have a great day!

**Comment by AdityaJ7** [comment]
> Can you @AdityaJ7 assign this issue to me? Thank you very much, and have a great day!

Sure @CaptainRoberts
