### ISSUE TITLE
PortScanner

### ISSUE THREAD

**Issue by jaesharma** [Python-World/Python_and_the_Web#216]
# Description
A python script to scan port on the local system or remotely.
you can specify the host IP and port number and the script will check if that port on the host system is open or closed.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
@jaesharma assigned to you

**Comment by jaesharma** [comment]
Can @AdityaJ7  assign this issue to me? Thank you very much, and have a great day!

**Comment by AdityaJ7** [comment]
Place this script  under the miscellaneous folder
