### ISSUE TITLE
Discord News Web Hook

### ISSUE THREAD

**Issue by Araon** [Python-World/Python_and_the_Web#217]
# Description
The Discord webhook will scrape the news website [inshort](https://inshorts.com/en/read/) and post a daily news update on the Selected Channel

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by Araon** [comment]
I think i can pull this off can I be assigned this issue

**Comment by AdityaJ7** [comment]
Cool @Araon you can go for it
