### ISSUE TITLE
Excel Columns Translator

### ISSUE THREAD

**Issue by Sahil-k1509** [Python-World/Python_and_the_Web#219]
# Description

Takes an excel file as an input. 
Then the original language of content and the language it should be translated to.
Finally the column names that need to be translated are taken as input. 
All the specified columns are translated and  new excel file is created in same folder.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by Sahil-k1509** [comment]
I would like to work on this. This has many practical applications. I myself used this to translate an excel from hindi to punjabi with acceptable errors(5-10rows) which is much more manageable and affordable than 400 rows.

**Comment by AdityaJ7** [comment]
> I would like to work on this. This has practical applications too. I myself used this to translate an excel from hindi to punjabi with acceptable errors(5-10rows) which is much more manageable and affordable than 400 rows.

Sure go for it

**Comment by Lakshitk** [comment]
I would like the documentation to be assigned to me
Thank you very much, and have a nice day!
