### ISSUE TITLE
HLTV.org WhatsApp bot

### ISSUE THREAD

**Issue by golu360** [Python-World/Python_and_the_Web#221]
# Description
Grab news from HLTV.org RSS Feed.
Parse it and Send it to a given WhatsApp number/ list of numbers using Twilio

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [ X] I have read the project guidelines.
- [ X] I have checked all the existing projects, before submitting a new project issue.
- [X ] I have checked previous issues to avoid duplicates.
- [X ] This issue will be meaningful for the project.

**Comment by golu360** [comment]
I can pull this one off if assigned to

**Comment by AdityaJ7** [comment]
> I can pull this one off if assigned to

Sure go for it

**Comment by rishu1722** [comment]
It is easy and my first open source contribution. You can bilieve and i can help?

**Comment by AdityaJ7** [comment]
> It is easy and my first open source contribution. You can bilieve and i can help?

this issue has been claimed
