### ISSUE TITLE
 Playstore Review Scrapper

### ISSUE THREAD

**Issue by swaroopmaddu** [Python-World/Python_and_the_Web#222]
# Description

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [x] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Assigned to you @swaroopmaddu
