### ISSUE TITLE
Geocoding

### ISSUE THREAD

**Issue by pyGitHub7** [Python-World/Python_and_the_Web#223]
# Description

It is a simple project based on geocoding. 

Geocoding is the process of converting addresses (like a street address) into geographic coordinates (like latitude and longitude), which you can use to place markers on a map, or position
the map. 

To completely understand this project you got to have basic knowledge about python, json, REST API and file handling. 

While running the code, first it asks for a address. After you enter the address it returns data in json which you can access and print a particular piece of information if you want to.
Returned data include latitute, longitude, place id, long name, short name, formatted address etc.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [x] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
@pyGitHub7 thanks for your interest but a similar script already exists in our collection at python-mini-projects
