### ISSUE TITLE
Scraping images from thispersondoesnotexist 

### ISSUE THREAD

**Issue by TasneemParveen** [Python-World/Python_and_the_Web#224]
# Description

Scraping specified number of images from thispersondoesnotexist and putting them in a specified directory on your computer.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X ] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X ] I have read the project guidelines.
- [X ] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X ] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
You can go for it @TasneemParveen
