### ISSUE TITLE
NASA Image of the Day Scraper

### ISSUE THREAD

**Issue by CaptainRoberts** [Python-World/Python_and_the_Web#225]
# Description

I have a python script that gets NASA's Astronomy Image of the Day that they post on their website. The image quality stays the same, no pixelation.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by CaptainRoberts** [comment]
I would like this issue to be assigned to me @AdityaJ7 .
Thank you very much, and have a nice day!

**Comment by AdityaJ7** [comment]
> I would like this issue to be assigned to me @AdityaJ7 .
> Thank you very much, and have a nice day!

Sure @CaptainRoberts

**Comment by nmeurer** [comment]
If you don't want to work on it any more just let me know. I'll do it for you.

**Comment by Lakshitk** [comment]
I would like the documentation to be assigned to me 
Thank you very much, and have a nice day!
