### ISSUE TITLE
News App 

### ISSUE THREAD

**Issue by KhushiGangopadhyay** [Python-World/Python_and_the_Web#230]
A News Website which shows the top news all categories and also with the feature of personalising your own feed and bookmarking important links
## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [ X] I have read the project guidelines.
- [ X] I have checked all the existing projects, before submitting a new project issue.
- [ X] I have checked previous issues to avoid duplicates.
- [ X] This issue will be meaningful for the project.

**Comment by KhushiGangopadhyay** [comment]
I would like to work on this issue, please assign it to me @AdityaJ7 , thank you.

**Comment by AdityaJ7** [comment]
> I would like to work on this issue, please assign it to me @AdityaJ7 , thank you.

Sure @KhushiGangopadhyay

**Comment by AdityaJ7** [comment]
> I would like to work on this issue, please assign it to me @AdityaJ7 , thank you.

Make sure to use Python

**Comment by KhushiGangopadhyay** [comment]
Yes , I will, thank you so much.
