### ISSUE TITLE
Shopify Web Scraper

### ISSUE THREAD

**Issue by xcodz-dot** [Python-World/Python_and_the_Web#232]
# Description

Shopify Web Scraper

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by xcodz-dot** [comment]
I wanted to be assigned to this, may I?

**Comment by AdityaJ7** [comment]
> I wanted to be assigned to this, may I?

sure @xcodz-dot

**Comment by xcodz-dot** [comment]
thanks

**Comment by AdityaJ7** [comment]
@xcodz-dot are u working on this??

**Comment by xcodz-dot** [comment]
Sorry, I will not be able to work cause my school examinations are going on and i have to pay attention to ht codeathon

**Comment by AdityaJ7** [comment]
> Sorry, I will not be able to work cause my school examinations are going on and i have to pay attention to ht codeathon
> 
> @AdityaJ7

OK no problem @xcodz-dot Good luck with the exams and codeathon

**Comment by Meghana-12** [comment]
Hey, can I work on this? @AdityaJ7

**Comment by AdityaJ7** [comment]
> Hey, can I work on this? @AdityaJ7

sure @Meghana-12

**Comment by Meghana-12** [comment]
Hey, could you confirm if this is legal? https://www.shopify.in/robots.txt most of the stuff is disallowed.

**Comment by AdityaJ7** [comment]
> Hey, could you confirm if this is legal? https://www.shopify.in/robots.txt most of the stuff is disallowed. @AdityaJ7

I guess it's not but I am not sure as @xcodz-dot opened this issue

**Comment by xcodz-dot** [comment]
noop it is not illegal. it is web scraper and it does not interfere with server data nor does it upload any data to server. it simply downloads and parses the data.

**Comment by xcodz-dot** [comment]
ok this is not stale

**Comment by xcodz-dot** [comment]
this is noot stale
