### ISSUE TITLE
File Organizer Script

### ISSUE THREAD

**Issue by officialpm** [Python-World/Python_and_the_Web#241]
# Description

Auto organizing files - images, music, executables, documents

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by officialpm** [comment]
Please assign this to me 💯

**Comment by Skr-suyash** [comment]
Hey, can I work on this issue

**Comment by AdityaJ7** [comment]
> Hey, can I work on this issue

It has been assigned already
