### ISSUE TITLE
Typing Test Autocomplete Bot Using Selenium

### ISSUE THREAD

**Issue by CaptainRoberts** [Python-World/Python_and_the_Web#247]
# Description

A typing test autocomplete bot using Selenium.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by CaptainRoberts** [comment]
I would like to be assigned to this issue @AdityaJ7 
Thank you and have a nice day!

**Comment by AdityaJ7** [comment]
> I would like to be assigned to this issue @AdityaJ7
> Thank you and have a nice day!

Sure @CaptainRoberts

**Comment by CaptainRoberts** [comment]
Hello @AdityaJ7 the bot says the issue is stale but I already uploaded the final working script for the project. 
Any information with regards to the matter will be appreciated. Thanks and have a nice day!

**Comment by AdityaJ7** [comment]
> Hello @AdityaJ7 the bot says the issue is stale but I already uploaded the final working script for the project.
> Any information with regards to the matter will be appreciated. Thanks and have a nice day!

Yes, you did that ah it occurred cause this issue wasn't linked to your or, no problem i am closing this
