### ISSUE TITLE
Make a random quote desktop notification script

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#25]
# Description

Create a script that shows a random quote as a notification on your desktop.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Rogue-Halo** [comment]
The python module "Plyer" is a good start for this. I'll grab this.

**Comment by AdityaJ7** [comment]
> The python module "Plyer" is a good start for this. I'll grab this.

Yes, you are right, assigning it to you @Rogue-Halo

**Comment by Rogue-Halo** [comment]
Great, this has been merged.  We can close this.

**Comment by AdityaJ7** [comment]
> Great, this has been merged. We can close this.

YOur PR was empty

**Comment by AdityaJ7** [comment]
@Rogue-Halo Please create a new Pr with the notification script 
Thanks

**Comment by Rogue-Halo** [comment]
Done 👍
