### ISSUE TITLE
Road Lanes Detection

### ISSUE THREAD

**Issue by adityagandhamal** [Python-World/Python_and_the_Web#250]
# Description

 Detecting road lanes using Python and OpenCV

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by adityagandhamal** [comment]
I would like to work on this. Please assign me the task.

**Comment by AdityaJ7** [comment]
> I would like to work on this. Please assign me the task.

Sure @adityagandhamal

**Comment by adityagandhamal** [comment]
Thank you!
