### ISSUE TITLE
Python script to solve the Sudoku efficently

### ISSUE THREAD

**Issue by jaesharma** [Python-World/Python_and_the_Web#253]
# Description

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by jaesharma** [comment]
hey @AdityaJ7 please assign this to me.

**Comment by rishu1722** [comment]
This is work i love you can assign me.

**Comment by AdityaJ7** [comment]
> This is work i love you can assign me.

This has been assigned to someone else
