### ISSUE TITLE
Scraping images from thisxdoesnotexist

### ISSUE THREAD

**Issue by GodSaveTheDoge** [Python-World/Python_and_the_Web#254]
# Description
Make a scraper for images in these sites => https://thisxdoesnotexist.com/

## Type of issue
- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by GodSaveTheDoge** [comment]
I'm working on it to be clear :laughing:

**Comment by GodSaveTheDoge** [comment]
to be precise i'll __probably__ add these sites:
- https://thisponydoesnotexist.net/
- https://vole.wtf/
- https://thishorsedoesnotexist.com/
- https://thisartworkdoesnotexist.com/
- https://thissnackdoesnotexist.com/
- https://thisvesseldoesnotexist.com/
- https://thispersondoesnotexist.com/ (i have to consider this since there is already an issue on this site so I'll probably skip it)
- https://thiscatdoesnotexist.com/
- https://www.thiswaifudoesnotexist.net/
- https://random.dog/ (these dogs do exist)

**Comment by piraces** [comment]
I will work on this if you are ok with it 😀
