### ISSUE TITLE
reading text from images using pytessaract

### ISSUE THREAD

**Issue by StarSeeker123** [Python-World/Python_and_the_Web#26]
# Description

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Are u working on it @StarSeeker123

**Comment by LakshyaShastri** [comment]
@AdityaJ7 Can you assign me to this

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Can you assign me to this

Sorry @LakshyaShastri but this issue has already been assigned to @StarSeeker123  if he doesn't submits a pr in the next 4 days than I will assign this issue to you

You can check the other unassigned issue or create your own issue if you want to suggest a script which is missing in our repo.

**Comment by StarSeeker123** [comment]
@AdityaJ7 Yes, I am working on it.
