### ISSUE TITLE
Convert HTML  to PDF

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#27]
# Description

Write a script to convert the HTML file to PDF format.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by tauseefmohammed2** [comment]
I would like to implement this. I have a question. Will the User Provide the HTML File in the form of a URL?

**Comment by AdityaJ7** [comment]
> I would like to implement this. I have a question. Will the User Provide the HTML File in the form of a URL?(For Eg. [www.github.com](http://www.github.com))

Yes, the user will provide HTML file

**Comment by Saujanya0910** [comment]
Hey, I would like to implement this as a contribution for hacktoberfest 2020, if that's possible. This is my first time contributing to open-source.

**Comment by AdityaJ7** [comment]
> Hey, I would like to implement this as a contribution for hacktoberfest 2020, if that's possible. This is my first time contributing to open-source.

Sorry @Saujanya0910 this issue has been claimed already

You can check the other unassigned issues

We will love to have a contribution from your side!!

**Comment by Saujanya0910** [comment]
Missed by a matter of minutes lol no problem. Thanks.

**Comment by AdityaJ7** [comment]
> Missed by a matter of minutes lol no problem. Thanks.

Yes, you can check #33 it is relatively easy!

**Comment by Saujanya0910** [comment]
Sure, I would like to implement it using a python script. Please assign it to me, I'll do it as a contribution for Hacktoberfest. Thanks!

**Comment by AdityaJ7** [comment]
> Sure, I would like to implement it using a python script. Please assign it to me, I'll do it as a contribution for Hacktoberfest. Thanks!

Please comment at that issue for reference!!

**Comment by AdeshChoudhar19** [comment]
This issue is marked stale. Can I work on this, if previously assigned contributor agrees?

**Comment by AdityaJ7** [comment]
> This issue is marked stale. Can I work on this, if @tauseefmohammed2 agrees?

We'll wait for a day or two and will assign it to you if the concerned person doesn't respond

**Comment by AnkDos** [comment]
@AdityaJ7  Assign me this .

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Assign me this .

sure
