### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Mysterious-Owl** [Python-World/Python_and_the_Web#277]
# Description
1. Can someone make script to submit certificates to linkedin from text file,<br>
2.  A script to login in my college website and submit attendance. http://moodle.mitsgwalior.in/
     Login is just post request with username and password, any ideas to how to login<br>
3. An application to track my screen usage on laptop

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

**Comment by ritesh-dt** [comment]
What would be in the text file for point number 1?

And also how does the attendance system work for the website?

**Comment by Mysterious-Owl** [comment]
> What would be in the text file for point number 1?
> 
> And also how does the attendance system work for the website?

text file or technically a json/xml file with keys and values as the certificate submission form has on LinkedIn
attendance system is, first login(form post request) and then go to respective teacher and then open the attendance section and then submit your attendance by checking the box infront of present, enter password if needed.
Any tutorial/resource on how to login to websites and handle cookies, would be appreciated
