### ISSUE TITLE
Scrape song lyrics with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#28]
# Description

Script to scrape the lyrics of a song when the name of the artist and the song is provided by the user.

## Type of issue
- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Tomyzon1728** [comment]
I'd love to work on this

**Comment by AdityaJ7** [comment]
> I'd love to work on this

Cool assigning it to you @Tomyzon1728

**Comment by Gautam-virmani** [comment]
I want to work on this project but I am new to all this can you help.

**Comment by AdityaJ7** [comment]
> I want to work on this project but I am new to all this can you help.

Sorry this issue has already been assigned to someone

**Comment by Gautam-virmani** [comment]
> > I want to work on this project but I am new to all this can you help.
> 
> Sorry this issue has already been assigned to someone

Sorry I am unable to understand what you want to say

**Comment by AdityaJ7** [comment]
> > > I want to work on this project but I am new to all this can you help.
> > 
> > 
> > Sorry this issue has already been assigned to someone
> 
> Sorry I am unable to understand what you want to say

You cant work on this issue

**Comment by Gautam-virmani** [comment]
> > > > I want to work on this project but I am new to all this can you help.
> > > 
> > > 
> > > Sorry this issue has already been assigned to someone
> > 
> > Sorry I am unable to understand what you want to say
> 
> You cant work on this issue

Ok

**Comment by Vyprath** [comment]
Hi. I'd like to do this

**Comment by AdityaJ7** [comment]
> Hi. I'd like to do this

ok

**Comment by AnkDos** [comment]
@AdityaJ7 Assign me this

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Assign me this

sure
