### ISSUE TITLE
NetCat implementation in python

### ISSUE THREAD

**Issue by jaesharma** [Python-World/Python_and_the_Web#280]
# Description

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by jaesharma** [comment]
hey @AdityaJ7 , assign this to me, will love to contribute.

**Comment by AyushRajSharma** [comment]
hey, i'm Ayush Raj, i am familiar with netCat and can contribute in it. please assign me.
