### ISSUE TITLE
Telegram Bot for Weather Info

### ISSUE THREAD

**Issue by namanshah01** [Python-World/Python_and_the_Web#285]
# Description
A telegram bot which will provide real time weather information to the user using a weather API in python

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by namanshah01** [comment]
Hey @AdityaJ7 please assign this issue to me, I would love to work on this

**Comment by AdityaJ7** [comment]
> Hey @AdityaJ7 please assign this issue to me, I would love to work on this

Sure @namanshah01
