### ISSUE TITLE
Extract and Group all links in a given page

### ISSUE THREAD

**Issue by TEMHITHORPHE** [Python-World/Python_and_the_Web#286]
# Description
Given a user supplied url, the script will crawl the url extracting all **page links** and gives an output, grouping the extracted links into either internal OR external links

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [ x] I have read the project guidelines.
- [ x] I have checked all the existing projects, before submitting a new project issue.
- [ x] I have checked previous issues to avoid duplicates.
- [x ] This issue will be meaningful for the project.

**Comment by schezfaz** [comment]
Hey, can I  work on this?

**Comment by TEMHITHORPHE** [comment]
i ccreated this so i can get assigned to it sir ... am already half way through

**Comment by Anshul275** [comment]
@TEMHITHORPHE  Are you up to this :)
As the issue is stale for 9 days.

If not, @AdityaJ7 , can you assign me this??

**Comment by AdityaJ7** [comment]
> @TEMHITHORPHE Are you up to this :)
> As the issue is stale for 9 days.
> 
> If not, @AdityaJ7 , can you assign me this??

@Anshul275 assigning to you

**Comment by TEMHITHORPHE** [comment]
nah!! am done!!!
