### ISSUE TITLE
Scrape / use api to get some jokes.

### ISSUE THREAD

**Issue by GodSaveTheDoge** [Python-World/Python_and_the_Web#289]
# Description

Use some joke api / scrape a site with jokes (like https://sv443.net/jokeapi/v2/).

## Type of issue

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by GodSaveTheDoge** [comment]
If you can assign me it ^-^

**Comment by Adam-94** [comment]
Any chance I could be assigned for this?

**Comment by AdityaJ7** [comment]
> If you can assign me it ^-^

SURE GO FOR IT

**Comment by AdityaJ7** [comment]
> Any chance I could be assigned for this?

sorry the issue creator claimed it first

**Comment by AdityaJ7** [comment]
@GodSaveTheDoge place it under API if you use an API otherwise under scraper
