### ISSUE TITLE
Make a Notepad clone with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#29]
# Description

Make a text editor like notepad with the help of Python.
.
## Type of issue

- [x] Feature (New Script)
- [x] Bug
- [x] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Rogue-Halo** [comment]
I've written one in Tkinter, I'd be happy to contribute it to this.

**Comment by AdityaJ7** [comment]
> I've written one in Tkinter, I'd be happy to contribute it to this.

Sure buddy, go on assigning it to you

**Comment by yuvraajnarula** [comment]
I would like to work on this. Can you assign me this issue?

**Comment by AdityaJ7** [comment]
> I would like to work on this. Can you assign me this issue?
Sorry but @Rogue-Halo  is already working on this issue @yuvraajnarula

**Comment by Rogue-Halo** [comment]
Actually, @yuvraajnarula can take this one. Don't want to be greedy and take them all when I'm already working on one 😂

**Comment by AdityaJ7** [comment]
ALright @yuvraajnarula  go ahead with this issue

**Comment by yuvraajnarula** [comment]
hi, can you please help me in what folder should I put my code after entering in the script folder?

**Comment by AdityaJ7** [comment]
> hi, can you please help me in what folder should I put my code after entering in the script folder?

Miscellaneous
