### ISSUE TITLE
social media scraping

### ISSUE THREAD

**Issue by mahendrarathore1742** [Python-World/Python_and_the_Web#294]
Download the social mdeia data like  videos and  phtotos using the python script !

**Comment by AdityaJ7** [comment]
which social media are u referring to @mahendrarathore1742 ?

If Instagram then don't make this because that kind of script already exists

**Comment by mahendrarathore1742** [comment]
> which social media are u referring to @mahendrarathore1742 ?
> 
> If Instagram then don't make this because that kind of script already exists

Youtube and facebook more  10+ social medias

**Comment by AdityaJ7** [comment]
> > which social media are u referring to @mahendrarathore1742 ?
> > If Instagram then don't make this because that kind of script already exists
> 
> Youtube and facebook more 10+ social medias

ok then go for it

**Comment by mahendrarathore1742** [comment]
I sent a pull request check it
