### ISSUE TITLE
Make a script to send telegram messages with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#30]
# Description

Script to send messages on telegram with the help of Python.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by ameyanrd** [comment]
Hi, I would like to work on it.

**Comment by AdityaJ7** [comment]
> Hi, I would like to work on it.

Sure buddy!!

**Comment by ameyanrd** [comment]
Where should the code be added? in `Scripts/Bots`?

**Comment by AdityaJ7** [comment]
> Where should the code be added? in `Scripts/Bots`?

Yes correct
