### ISSUE TITLE
An Organiser application using Python and Qt5

### ISSUE THREAD

**Issue by swaroopmaddu** [Python-World/Python_and_the_Web#317]
# Description
  - New project organizer application using python and Qt5
  - Organiser application to plan your days and todos

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [X] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by tusharnankani** [comment]
Please rename your issue name, according to the project-name! @swaroopmaddu

**Comment by swaroopmaddu** [comment]
> Please rename your issue name, according to the project-name! @swaroopmaddu 

Done
