### ISSUE TITLE
Scrape Times of India website 

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#32]
# Description

Scrape news from the Times of India website as per the category of news provided by the user

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by ishan-chaudhary** [comment]
Hey can you assign me this issue

**Comment by AdityaJ7** [comment]
> Hey can you assign me this issue

Sure @ishan-chaudhary assigning it to you

**Comment by Rishav0907** [comment]
can I work on it?

**Comment by ishan-chaudhary** [comment]
I am not able to push my code on the new branch it is prompting permission denied

**Comment by ishan-chaudhary** [comment]
I have added my code, please accept my pull request.
