### ISSUE TITLE
Create the Flames Game with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#33]
# Description

Create a command-line Flames Game which takes two names as input and calculates the flames between them. 

Visit the below website to know the logic behind this game:
[Flames Logic](http://flamesgame.appspot.com/algorithm)

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Saujanya0910** [comment]
I would like to work on this issue. Reference to my comment on issue #27

**Comment by AdityaJ7** [comment]
> I would like to work on this issue. Reference to my comment on issue #27

Assigning it to you @Saujanya0910

**Comment by tusharnankani** [comment]
Fixed in PR #54
