### ISSUE TITLE
COVID-19 Scrapper

### ISSUE THREAD

**Issue by YASHBRO** [Python-World/Python_and_the_Web#330]
# Everything on COVID-19

- This is a *better scrapper* for generating stats for COVID-19 as in this one will display the following stats:
    1. **COVID stats of the world**
    2. **COVID stats of top 10 countries**
    3. **COVID stats for any requested countries**

- As I'll add a `.exe` along with the source code( `.py` file), so it will have no dependencies.

- If you want it to have more features on COVID-19, you can ask me, I'll try my best to add them

## Type of issue

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by TediaN97** [comment]
i would take this issue

**Comment by TediaN97** [comment]
can i take this issue ??

**Comment by YASHBRO** [comment]
> can i take this issue ??

I'm sorry, I already started working on it and its almost done.
