### ISSUE TITLE
To-Do-App-with-a-timer (windows application) 

### ISSUE THREAD

**Issue by Ishaan-0098** [Python-World/Python_and_the_Web#333]
# Description

A to do windows application with a timer and a decent gui.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X ] I have read the project guidelines.
- [ X] I have checked all the existing projects, before submitting a new project issue.
- [ X] I have checked previous issues to avoid duplicates.
- [ X] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Sure @Ishaan-0098 you can work on it

**Comment by TEMHITHORPHE** [comment]
commenting just to get emailed|tagged when this is done.
