### ISSUE TITLE
Youtube Downloader

### ISSUE THREAD

**Issue by swaroopmaddu** [Python-World/Python_and_the_Web#338]
# Description
   - Download youtube videos with pythin

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [X] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

![image](https://user-images.githubusercontent.com/24986270/95015116-e26b9980-0668-11eb-9c8d-c25783254def.png)

**Comment by mahendrarathore1742** [comment]
can i work on it.

**Comment by AdityaJ7** [comment]
> can i work on it.

Somebody is working on it already

**Comment by mahendrarathore1742** [comment]
> > can i work on it.
> 
> Somebody is working on it already
OK
