### ISSUE TITLE
Code Forces problem scraper

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#34]
# Description

Scrape the problem statement from the Code Forces website as per the problem code provided by the user.
Save the result in a text file.

## Type of issue
- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by roopeshvs** [comment]
Hello, I'd love to contribute to this.

**Comment by AdityaJ7** [comment]
> Hello, I'd love to contribute to this.

Sure Buddy!!
