### ISSUE TITLE
Simple cryptocurrency convertor with python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#347]
# Description

Create a command-line based cryptocurrency convertor with Python

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by abhinavanand123** [comment]
Hello @AdityaJ7 I want to work on this issue
So can u plz assign me this so that I can initiate the PR

**Comment by AdityaJ7** [comment]
> Hello @AdityaJ7 I want to work on this issue
> So can u plz assign me this so that I can initiate the PR

Sure @abhinavanand123

**Comment by abhinavanand123** [comment]
@AdityaJ7 I have initiated the PR.

**Comment by abhinavanand123** [comment]
@AdityaJ7 I have made the necessary changes.
Can you plz go through it??

**Comment by AdityaJ7** [comment]
@abhinavanand123 ok i am checking it

**Comment by abhinavanand123** [comment]
@AdityaJ7 can u plz help me out with placing my folder to API directory.
As I know a very little about it.

**Comment by AdityaJ7** [comment]
@abhinavanand123  go to your local clone of the repo and move your folder into API folder, then commit the changes and push them

**Comment by abhinavanand123** [comment]
Shall I create a new API folder or Is there a existing API folder

**Comment by AdityaJ7** [comment]
@abhinavanand123 there is an existing folder

**Comment by abhinavanand123** [comment]
@AdityaJ7 I am not able to proceed.
I have no idea where I am going wrong

**Comment by AdityaJ7** [comment]
@abhinavanand123 you have placed it correctly now but you forgot to remove it from the old place so now top instances of same files are present in your or in two different locations

**Comment by abhinavanand123** [comment]
yes exactly so how to remove it from there @AdityaJ7 
Can u help me out

**Comment by AdityaJ7** [comment]
> yes exactly so how to remove it from there @AdityaJ7
> Can u help me out

Yes i will remove the duplicates

**Comment by abhinavanand123** [comment]
okay sure @AdityaJ7 
Next what has to be done let me know

**Comment by AdityaJ7** [comment]
@abhinavanand123 I have suggested the changes there if you still have doubt then do let me know

**Comment by abhinavanand123** [comment]
> @abhinavanand123 I have suggested the changes there if you still have doubt then do let me know

Okay sure

**Comment by abhinavanand123** [comment]
@AdityaJ7 I have made the changes requested by you
Can you plz once go through it and do let me know
