### ISSUE TITLE
LeetCode Problem Scraper

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#348]
# Description

Scrape problem statement from leetcode based on the problem code provided by the user.

Save the result in txt or pdf file.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by MaheshBharadwaj** [comment]
I would like to try this one, will un-assign if unable to complete

**Comment by MaheshBharadwaj** [comment]
I would like to try this one @AdityaJ7 , if unable to complete will un-assign myself

**Comment by officialpm** [comment]
I would like to work on it! 💯

**Comment by SyahirahWanMin** [comment]
please assign me for this task .Thanks
