### ISSUE TITLE
Set wallpaper through Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#349]
# Description

Create a simple script which takes a jpeg file and sets it as your system wallpaper/desktop background

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Two people can work on this one for Linux other for Windows

**Comment by symtalha14** [comment]
Hello, I would like to contribute to this. Please assign me so that I can initiate a PR.

**Comment by AdityaJ7** [comment]
> Hello, I would like to contribute to this. Please assign me so that I can initiate a PR.

Which Os you want to work for?

**Comment by symtalha14** [comment]
> > Hello, I would like to contribute to this. Please assign me so that I can initiate a PR.
> 
> Which Os you want to work for?

For Windows

**Comment by symtalha14** [comment]
Please Review my PR

**Comment by ritesh-dt** [comment]
I would like to work on changing the background on Linux based operating systems.

**Comment by AdityaJ7** [comment]
> I would like to work on changing the background on Linux based operating systems.

cool @ritesh-dt  go for it

**Comment by ritesh-dt** [comment]
Should I use the folder and files created by @symtalha14 ? So the same file could work for Windows and Linux
I'll rename the folder from "Windows_Wallpaper_Changer" to "Wallpaper_Changer" and make changes to background.py

**Comment by AdityaJ7** [comment]
> Should I use the folder and files created by @symtalha14 ? So the same file could work for Windows and Linux
> I'll rename the folder from "Windows_Wallpaper_Changer" to "Wallpaper_Changer" and make changes to background.py

create a separate folder with changes in the files as per linux
