### ISSUE TITLE
Create a script to convert JSON files to Excel(.xlsx)

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#35]
# Description

Script to convert JSON files to excel format.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Meghana-12** [comment]
I would like to work on this issue !

**Comment by AdityaJ7** [comment]
> I would like to work on this issue !

Sure!!

**Comment by Meghana-12** [comment]
Thanks :)
