### ISSUE TITLE
Find Repository Size with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#350]
# Description

Create a script to find the size of a GitHub repository by using the Github rest API

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by dhiganthrao** [comment]
Has this issue already been claimed? If not, may I work on this? I'd like to try working with the GitHub REST API and this seems like a good first start.

**Comment by AdityaJ7** [comment]
assigned to you @dhiganthrao

**Comment by dhiganthrao** [comment]
Thanks! Will try doing it to the best of my ability. Any deadlines or can I work on this leisurely? (Until Hacktoberfest ends, that is)

**Comment by AdityaJ7** [comment]
> Thanks! Will try doing it to the best of my ability. Any deadlines or can I work on this leisurely? (Until Hacktoberfest ends, that is)

7 days

**Comment by dhiganthrao** [comment]
Just enquiring, you don't need a final solution in the form of an application right? Would a .py file be enough?

**Comment by AdityaJ7** [comment]
> Just enquiring, you don't need a final solution in the form of an application right? Would a .py file be enough?

Yes a .py file is enough, do attach a readme file along with a screenshot of the script I action

**Comment by dhiganthrao** [comment]
@AdityaJ7 whenever you're free, do review my pull request. Thanks!

**Comment by dhiganthrao** [comment]
@AdityaJ7 thanks for merging my files! Is there anything else I should do to get the hacktoberfest-accepted label for this? Also, if I make pull requests on other issues in this repo, will it be counted as another separate pull request added to my count?
