### ISSUE TITLE
Scrape live cricket scores from Cricbuzz

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#352]
# Description

Create a script to scrape live scores from cricbuzz

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Anshul275** [comment]
I am up for this. Please assign me this issue :)
