### ISSUE TITLE
Scrape Cricket News from Cricbuzz

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#354]
# Description

Scrape the latest news from cricbuzz and store it in a text file.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by kartavyashankar** [comment]
I am ready for this, please assign me this issue

**Comment by AdityaJ7** [comment]
> I am ready for this, please assign me this issue

Sure @kartavyashankar

**Comment by kartavyashankar** [comment]
@AdityaJ7 
Should I attach the generated .txt file also?
