### ISSUE TITLE
Send sms using Twilio API with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#36]
# Description

Send SMS to people by creating a free Twilio account, use Python for scripting purpose.

## Type of issue
- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Ajay-Raj-S** [comment]
Hello @AdityaJ7 , Can I work on this issue? It would be nice that I would also gain experience from this.

**Comment by AdityaJ7** [comment]
> Hello @AdityaJ7 , Can I work on this issue? It would be nice that I would also gain experience from this.

Sure you can go ahead with it!!!

**Comment by Ajay-Raj-S** [comment]
so can you assign it to me.

**Comment by AdityaJ7** [comment]
Assigned it to you @Ajay-Raj-S

**Comment by myworkcircle** [comment]
I have worked on twilio can u assign me this

**Comment by AdityaJ7** [comment]
> I have worked on twilio can u assign me this

sorry this issue has been claimed already

**Comment by Ajay-Raj-S** [comment]
Hello @AdityaJ7 , please review my code I have made the pull request.
