### ISSUE TITLE
Wifi Speed tester with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#37]
# Description

Create a script that provides the download and upload speed of your Wifi.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdeshChoudhar19** [comment]
I would like to contibute using Python.

**Comment by AdityaJ7** [comment]
> I would like to contibute using Python.

Sure buddy! assigning it to you @AdeshChoudhar19

**Comment by AdeshChoudhar19** [comment]
Thank you!

**Comment by AdeshChoudhar19** [comment]
I'm new to open source, how to send you code, should I send the file over here?

**Comment by AdityaJ7** [comment]
> I'm new to open source, how to send you code, should I send the file over here?
You will have to fork this repository and submit a Pull Request The detailed explanation has been provided in the README File of the repository!!

You can check it [here](https://github.com/Python-World/Python_and_the_Web/blob/master/README.md)

**Comment by AdeshChoudhar19** [comment]
Thanks man!

**Comment by AdityaJ7** [comment]
> I'm new to open source, how to send you code, should I send the file over here?

You will have to fork this repository and submit a Pull Request The detailed explanation has been provided in the README File of the repository!!

You can check it [here](https://github.com/Python-World/Python_and_the_Web/blob/master/README.md)

**Comment by AdityaJ7** [comment]
> Thanks man!

No problem buddy you can comment here If on our WhatsApp group if you face any other issue

**Comment by AdeshChoudhar19** [comment]
I have completed the code, in which folder should I place the file?

**Comment by AdityaJ7** [comment]
> I have completed the code, in which folder should I place the file?

Miscellaneous

**Comment by AdeshChoudhar19** [comment]
Ok. Thanks again.

**Comment by AdityaJ7** [comment]
> Ok. Thanks again.

No problem buddy!!

**Comment by AdeshChoudhar19** [comment]
I have submitted a pull request. Please check it out and tell me if any changes are required.
