### ISSUE TITLE
Scrape algo trading articles from quant finance websites

### ISSUE THREAD

**Issue by shivanshsinghal107** [Python-World/Python_and_the_Web#373]
# Description

Scrape top algorithmic trading articles and mathematical finance articles from Quantopian, Quantstart, Quantocracy.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by shivanshsinghal107** [comment]
I am working on this issue, can you assign me, please.

**Comment by AdityaJ7** [comment]
> I am working on this issue, can you assign me, please.

You are assigned already
