### ISSUE TITLE
Scrape top torrents 

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#38]
# Description

Scrape top trending torrents as per the category provided by the user.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by maddypie** [comment]
Which sites do you consider as top torrents sites? Is there any source for the same?

**Comment by AdityaJ7** [comment]
> Which sites do you consider as top torrents sites? Is there any source for the same?

You can use 1337x , piratebay or prostylex

**Comment by AdityaJ7** [comment]
Should I assign this issue to you @maddypie ??

**Comment by maddypie** [comment]
Yes, I will try my best.

**Comment by AdityaJ7** [comment]
> Yes, I will try my best.

Alright, buddy, you can comment here if you face any issue

**Comment by maddypie** [comment]
@AdityaJ7, Please un-assign me. I failed to find a solution and moreover I am engaged in some other work. 
Sorry.

**Comment by AdityaJ7** [comment]
> @AdityaJ7, Please un-assign me. I failed to find a solution and moreover I am engaged in some other work.
> Sorry.

Ok no problem!

**Comment by anandhakrishnanaji** [comment]
Can I take up this issue?

**Comment by AdityaJ7** [comment]
> Can I take up this issue?

Sure @anandhakrishnanaji

**Comment by AdityaJ7** [comment]
@anandhakrishnanaji  are you working on this??

**Comment by anandhakrishnanaji** [comment]
I am sorry, I was busy with some other work. Please unassign me.

**Comment by Anshul275** [comment]
@AdityaJ7 Can i work on this??
