### ISSUE TITLE
Write a script to detect number plates 

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#380]
# Description

Write a script to detect LICENSE number plates in an image using Python

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by TEMHITHORPHE** [comment]
As in vehicle plate numbers!!?? .... 
if so, can't wait for someone to get this done! ... i really really need this ... lol ... and to see the implementation

**Comment by shreyamodi1999** [comment]
Hey can you assign this to me ? I would love to give this a try
