### ISSUE TITLE
Scrape news from Google News

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#381]
# Description

Create a script to scrape the latest news from Google news.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by TEMHITHORPHE** [comment]
which specific beat should be covered ... just checked the site now and it has a lot of sections!

**Comment by TEMHITHORPHE** [comment]
![Screenshot (248)](https://user-images.githubusercontent.com/19387360/95100220-cb8c7c00-0728-11eb-890a-ff22ee097288.png)

So should the script just scrape the **latest** news or still ask user for more fine tuning?

**Comment by TEMHITHORPHE** [comment]
... was hoping you wouldn't say that ... that's a lot of code ... lol

**Comment by kartavyashankar** [comment]
@AdityaJ7 
I am ready for this, please assign me this issue
