### ISSUE TITLE
Scrape articles from the Cricket Monthly

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#382]
# Description

Write a script to scrape articles from this website - [Cricket Monthly](https://www.thecricketmonthly.com/)

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Skr-suyash** [comment]
Which format the output data should be in (csv, word etc.)?

**Comment by AdityaJ7** [comment]
> Which format the output data should be in (csv, word etc.)?

CSV or txt

**Comment by kartavyashankar** [comment]
@AdityaJ7 
Can you assign me this issue?
