### ISSUE TITLE
Github-Folder-Download-Tool

### ISSUE THREAD

**Issue by TEMHITHORPHE** [Python-World/Python_and_the_Web#383]
# Description

A python tool that takes a **github folder** as input and **downloads recursively everything in the folder**

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [ x] I have read the project guidelines.
- [ x] I have checked all the existing projects, before submitting a new project issue.
- [ x] I have checked previous issues to avoid duplicates.
- [x ] This issue will be meaningful for the project.

**Comment by dhiganthrao** [comment]
Has this issue been assigned already?

**Comment by AdityaJ7** [comment]
> Has this issue been assigned already?

it has been assigned
