### ISSUE TITLE
(PTC-W0010) File opened without the `with` statement

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#386]
## Description
Opening a file using `with` statement is preferred as function `open` implements the context manager protocol that releases the resource when it is outside of the `with` block. Not doing so requires you to manually release the resource.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Python-World/Python_and_the_Web/issue/PTC-W0010/occurrences/](https://deepsource.io/gh/Python-World/Python_and_the_Web/issue/PTC-W0010/occurrences/)

**Comment by fuzzmz** [comment]
@AdityaJ7, I can have a PR ready in a couple of minutes. Mind assigning this to me?

**Comment by AdityaJ7** [comment]
> @AdityaJ7, I can have a PR ready in a couple of minutes. Mind assigning this to me?

Sure, go ahead with this

**Comment by AdityaJ7** [comment]
> @AdityaJ7, I can have a PR ready in a couple of minutes. Mind assigning this to me?

Comment here if you have doubts about the exact files that need to be fixed
