### ISSUE TITLE
Create a basic discord Bot with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#39]
# Description

Create a simple bot with python that shares random quotes whenever a user says - **quotes, please**

## Type of issue

- [x] Feature (New Script)
- [x] Bug
- [x] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Meghana-12** [comment]
I would like to try this issue out!

**Comment by AdityaJ7** [comment]
> I would like to try this issue out!

Sure ma'am assigning it to you

**Comment by p014ri5** [comment]
I'd love to work on this.. 👍🏻

**Comment by GhostUser** [comment]
Can I still contribute by making a discord bot and submitting he code.

**Comment by AdityaJ7** [comment]
> Can I still contribute by making a discord bot and submitting he code.

Ah sorry @GhostUser  this issue has been claimed already !! 

If you have another bot idea different from this than you can create a comment with your idea in this [issue](https://github.com/Python-World/Python_and_the_Web/issues/31)

**Comment by GhostUser** [comment]
okay

**Comment by parzuko** [comment]
Hey i've made a discord music bot before, can i make another one ?

**Comment by AdityaJ7** [comment]
> Hey i've made a discord music bot before, can i make another one ?

This issue has been claimed but if you want to create a discord bot whose functionality is different from this one then you can comment about that idea of yours in this issue

**Comment by Meghana-12** [comment]
Why is this issue closed @AdityaJ7 ?
