### ISSUE TITLE
Simple speech to text program using Python

### ISSUE THREAD

**Issue by reddymahendra52** [Python-World/Python_and_the_Web#392]
# Speech Recognition using Python

A simple program which tells the uses of PyAudio for Speech Recognition.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ X] Feature (New Script)
- [ ] Bug
- [X ] Documentation

## Checklist:

- [ X] I have read the project guidelines.
- [ X] I have checked all the existing projects, before submitting a new project issue.
- [X ] I have checked previous issues to avoid duplicates.
- [X ] This issue will be meaningful for the project.

**Comment by reddymahendra52** [comment]
Can you please assign me this issue i want to do it...

**Comment by tusharnankani** [comment]
Hi @reddymahendra52 

Appreciate your thought for contributing to this, but this script has already been added in our other [repository.](https://github.com/Python-World/python-mini-projects)

Feel free to contribute to our other issues or open issues!

**Comment by reddymahendra52** [comment]
We can only add scripts??
Or we can add tutorial like explaining a certain topic with mardown and jupyternotebook.??

**Comment by AdityaJ7** [comment]
closing this 
@reddymahendra52 
Only scripts, you can use Jupyter notebooks for data analysis projects or image processing projects 

Thanks
