### ISSUE TITLE
Scrape MLB player stats

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#4]
# Description

Write a script to scrape the stats of a user-defined MLB player and store them in CSV file.
You can use this website: [MLB Players](https://www.mlb.com/players)

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Tomyzon1728** [comment]
Can I take up this project

**Comment by AdityaJ7** [comment]
> Can I take up this project

Sure

**Comment by Tomyzon1728** [comment]
@AdityaJ7 I've created a PR , looking foward to you merging it.
