### ISSUE TITLE
Scrape DevFest India 2020 Schedule 

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#412]
# Description

Scrape Devfest India 2020 Schedule and store it in a csv file.
CSV Columns must be - Name of event, date, timings, tag, author
Refer this website - [Devfest India Schedule](https://devfestindia.com/schedule)

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Anshul275** [comment]
I would like to work. Assign me the issue :)

**Comment by Anshul275** [comment]
@AdityaJ7 Should I also attach the generated csv file
