### ISSUE TITLE
Screenshot using python

### ISSUE THREAD

**Issue by sanketchaudhari10** [Python-World/Python_and_the_Web#446]
# Description
 A simple program that will take a screenshot on your command

## Type of issue:
-  *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by dhiganthrao** [comment]
If there's no one else assigned, may I work on this?

**Comment by sanketchaudhari10** [comment]
@dhiganthrao I am working on it!! Its a one man thing, thanks!!!

**Comment by dhiganthrao** [comment]
@sanketchaudhari10 ah ok no worries

**Comment by pratik-choudhari** [comment]
@AdityaJ7 Can I be assigned to this?

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Can I be assigned to this?

Sure
