### ISSUE TITLE
Pomodoro Timer using Python

### ISSUE THREAD

**Issue by dhiganthrao** [Python-World/Python_and_the_Web#447]
# Description

A simple script that notifies you every 25 minutes to take a break and divide your work into small chunks. It will run in the background and sends notifications every 25 minutes, with 5 minute breaks in between.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by dhiganthrao** [comment]
Hi, is it possible to review this issue and check if it's suitable for this repository so I may start working on it as soon as possible? Since I'm assigned to this repo, I'll be working on this if it gets accepted. Thanks!

**Comment by AdityaJ7** [comment]
> Hi, is it possible to review this issue and check if it's suitable for this repository so I may start working on it as soon as possible? Since I'm assigned to this repo, I'll be working on this if it gets accepted. Thanks!

You can do ahead with it

**Comment by dhiganthrao** [comment]
Since this Issue has been resolved by merging my pull request into this repository, I am closing this Issue. Cheers!
