### ISSUE TITLE
download youtube audio

### ISSUE THREAD

**Issue by chavarera** [Python-World/Python_and_the_Web#45]
# Description
Accept YouTube video link and download audio file

## Type of issue
- [X] Feature (New Script)
- [x] Bug
- [x] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by pranav6670** [comment]
I can do this. Can you assign me this issue?

**Comment by AdeshChoudhar19** [comment]
I would like to work on this.

**Comment by myworkcircle** [comment]
I would like to work on this, i have previousely worked on python projects related to audio seperation from videos and have created plugins

**Comment by AdityaJ7** [comment]
> I would like to work on this, i have previousely worked on python projects related to audio seperation from videos and have created plugins

This issue has been assigned already

**Comment by AdeshChoudhar19** [comment]
@AdityaJ7 Thank you for assigning me! I have started working on it, I think this project will need some time, what is the time limit for completing this? I'll update you regularly.

**Comment by Vyprath** [comment]
Hey, I'd love to do this task!

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Thank you for assigning me! I have started working on it, I think this project will need some time, what is the time limit for completing this? I'll update you regularly.

Complete before 7 days

**Comment by AdityaJ7** [comment]
> Hey, I'd love to do this task!

Hi @Vyprath thanks for showing interest in this issue but it has already been claimed by someone else, please check other unclaimed issue or create your own issue if you think our repos are , missing any script 

Thanks

**Comment by AdeshChoudhar19** [comment]
> > @AdityaJ7 Thank you for assigning me! I have started working on it, I think this project will need some time, what is the time limit for completing this? I'll update you regularly.
> 
> Complete before 7 days

Yes, I think that is enough!

**Comment by AdeshChoudhar19** [comment]
Please give me some more time.

**Comment by AdeshChoudhar19** [comment]
I have submitted a pull request. Please check and sorry for the delay.
