### ISSUE TITLE
convert UNIX time stamp to human readable format

### ISSUE THREAD

**Issue by chavarera** [Python-World/Python_and_the_Web#46]
# Description

convert UNIX time stamp to human readable format

Unix Timestamp

![Screenshot from 2020-09-30 22-56-01](https://user-images.githubusercontent.com/33047641/94719010-324c1700-0370-11eb-99da-b96949b5bacb.png)

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [X] Bug
- [X] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by pranav6670** [comment]
Can you assign me this issue?

**Comment by chavarera** [comment]
go for it @pranav6670

**Comment by pranav6670** [comment]
> go for it @pranav6670
Great! Thanks, man!
