### ISSUE TITLE
[New Script] Soccer League Table CLI for major leagues

### ISSUE THREAD

**Issue by MaheshBharadwaj** [Python-World/Python_and_the_Web#460]
# Description
Display current standings in the league requested by using a free API or scraping a webpage.
## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by MaheshBharadwaj** [comment]
If this issue is okay, I will start working on it :D

**Comment by King-Del-ErnestO** [comment]
Please I want to be assigned to this project
