### ISSUE TITLE
Image to base64 encoding and vice versa

### ISSUE THREAD

**Issue by chavarera** [Python-World/Python_and_the_Web#47]
# Description
Image to base64 encoding and vice versa

## Type of issue
- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by pranav6670** [comment]
Can I work on this issue? Thank You!

**Comment by AdityaJ7** [comment]
> Can I work on this issue? Thank You!

Sure buddy @pranav6670

**Comment by pranav6670** [comment]
> > Can I work on this issue? Thank You!
> 
> Sure buddy @pranav6670

Great! Thanks, bro.
