### ISSUE TITLE
Scrape Upcoming Codechef contests

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#471]
# Description

Use python to scrape the upcoming codechef contests and store the result in a csv or text file.
.
## Type of issue

- [X] Feature (New Script)

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by ritesh-dt** [comment]
I would like to work on this issue? @AdityaJ7 Could you assign this to me?

**Comment by ritesh-dt** [comment]
@AdityaJ7 Thanks!!

**Comment by ritesh-dt** [comment]
@AdityaJ7 Can this issue be worked on?
It's marked as up-for-grab and stale as well. [Music Player](https://github.com/Python-World/Python_and_the_Web/issues/16)

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Can this issue be worked on?
> It's marked as up-for-grab and stale as well. [Music Player](https://github.com/Python-World/Python_and_the_Web/issues/16)

Yes you can work on it
