### ISSUE TITLE
Key Logger with Python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#472]
# Description

Create a simple key logger with Python.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by code-netizen** [comment]
i want to work on this

**Comment by code-netizen** [comment]
i have made PR right now have a look plz tell if any change need

**Comment by ritik-malik** [comment]
Hi, I saw the keylogger,
and I was thinking to add some more features to it like -
1. Making a secret end signal which automatically closes the hidden script
2. Will make a cross compiled binary for multi platform
3. Managing the CPU load
4. Save the output to a file
Can this be accepted as an issue?

**Comment by AdityaJ7** [comment]
> Hi, I saw the keylogger,
> and I was thinking to add some more features to it like -
> 
> 1. Making a secret end signal which automatically closes the hidden script
> 2. Will make a cross compiled binary for multi platform
> 3. Managing the CPU load
> 4. Save the output to a file
>    Can this be accepted as an issue?

Sure you can go ahead with the improvements

**Comment by ritik-malik** [comment]
2 more doubts before proceeding - 
1. So do I make a new directory or change in the old one?
2. Will this be counted towards hactoberfest?

**Comment by AdityaJ7** [comment]
> 2 more doubts before proceeding -
> 
> 1. So do I make a new directory or change in the old one?
> 2. Will this be counted towards hactoberfest?

make changes in the already existing code

yes it will be counted
