### ISSUE TITLE
LInkedin Post Scraper

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#473]
# Description

Scrape the content of a LinkedIn post. The post must be user defined

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by kartavyashankar** [comment]
@AdityaJ7 
I will like to try this issue. Please assign me.
