### ISSUE TITLE
Scrape posts from Quora

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#474]
# Description

Use python to scrape posts from quora and save the result in a txt or pdf file

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by 20prince12** [comment]
I can work if it is still up.

**Comment by divya2703** [comment]
I would like to work on this issue.
