### ISSUE TITLE
Automate Zoom meetings

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#475]
# Description

Python script that starts a zoom meeting for you provided the id and password form the console.
Keep mic and camera off.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Anshul275** [comment]
Can i work on this :)
