### ISSUE TITLE
 face mask detection detection

### ISSUE THREAD

**Issue by chavarera** [Python-World/Python_and_the_Web#48]
# Description

 Detects if a person is wearing a mask primarily in public places or not.

## Type of issue
- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by hacky1997** [comment]
I want to work on this! Could you please assign me?

**Comment by chavarera** [comment]
sure @hacky1997 go for it

**Comment by hacky1997** [comment]
@chavarera I have done this project before. How can I upload it here? Just doing normal push origin?

**Comment by chavarera** [comment]
@hacky1997 yes
