### ISSUE TITLE
twitter sentiment analysis

### ISSUE THREAD

**Issue by chavarera** [Python-World/Python_and_the_Web#49]
# Description
Twitter sentiment analysis

## Steps
- [ ] Read hashtag from input
- [ ] Find top 500 tweets
- [ ] create sentimental analysis

## Type of issue
- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by schezfaz** [comment]
Hey, can I work on this issue?
