### ISSUE TITLE
Create application to save Google keep note to CSV file and vice versa

### ISSUE THREAD

**Issue by chavarera** [Python-World/Python_and_the_Web#5]
# Description

Create a command-line application/ script to save google keep notes to CSV file and vice versa.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by grplyler** [comment]
Hi there. By application, do you mean a command line application?

**Comment by AdityaJ7** [comment]
> Hi there. By application, do you mean a command line application?

Yes

**Comment by grplyler** [comment]
Ok sweet, is there any particular rational for using csv? Should the application be more of a note taking application linked to Google Keep or more of an batch import/export tool for Google Keep? Just trying to understand the scope. I'd love to contribute for Hacktoberfest 2020.

**Comment by AdityaJ7** [comment]
> Ok sweet, is there any particular rational for using csv? Should the application be more of a note taking application linked to Google Keep or more of an batch import/export tool for Google Keep? Just trying to understand the scope. I'd love to contribute for Hacktoberfest 2020.

An import/export tool for google keep

Thanks for showing interest in our repository, we will be happy to receive a contribution from you.

**Comment by grplyler** [comment]
Ok, that sounds actually useful! It may take a couple days because I'll probably have to do OAuth2 authentication, but I'll take this one on!

**Comment by AdityaJ7** [comment]
> Ok, that sounds actually useful! It may take a couple days because I'll probably have to do OAuth2 authentication, but I'll take this one on!

Cool, you can take your time, I am assigning this issue to you, Good luck!

**Comment by AdeshChoudhar19** [comment]
This issue is marked stale. Can I work on this if @grplyler agrees?

**Comment by AdityaJ7** [comment]
> This issue is marked stale. Can I work on this if @grplyler agrees?

We'll wait for a day or two and will assign it to you if the concerned person doesn't responds
