### ISSUE TITLE
Random Album Suggestion API

### ISSUE THREAD

**Issue by AnkDos** [Python-World/Python_and_the_Web#506]
# Description

An API to suggest a random album from Rolling Stone's 500 Greatest Albums of All Time dateset. The main aim behind this API is to showcase the proper folder structure to organize code in a flask project using blueprint as I came across lot of good flask projects where routes and logic written in a single file .Will push it on heroku and will add the required files used while deploying. Also will be using class based view (Pluggable Views)  to make the code look more organized .

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by AnkDos** [comment]
@tusharnankani  please assign me this.

**Comment by tusharnankani** [comment]
It is already assigned, thanks to our very own `github-actions` bot.
You can start working on it! ^_^
