### ISSUE TITLE
Job Site Scraping

### ISSUE THREAD

**Issue by tenzu15** [Python-World/Python_and_the_Web#509]
# Description

Given a user query, scrape and return all available position from a set of job related websites. #31

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Feature (New Script)
- [ ] Documentation

## Checklist:

- [ ] I have read the project guidelines.
- [ ] I have checked all the existing projects, before submitting a new project issue.
- [ ] I have checked previous issues to avoid duplicates.
- [ ] This issue will be meaningful for the project.

Steps -

- [ ] Finalize Websites
- [ ] Implement code
- [ ] Testing for possible  
- [ ] Documentation

**Comment by tusharnankani** [comment]
You could also try contributing to one of our organization's project: [Joble](https://github.com/Python-World/Joble)

**Comment by tenzu15** [comment]
> You could also try contributing to one of our organization's project: [Joble](https://github.com/Python-World/Joble)

Sure!

**Comment by tusharnankani** [comment]
> Given a user query, scrape and return all available position from a set of job related websites

Are you working on it? @tenzu15

**Comment by tenzu15** [comment]
> > Given a user query, scrape and return all available position from a set of job related websites
> 
> Are you working on it? @tenzu15

Yes, working on it
