### ISSUE TITLE
stock scraper

### ISSUE THREAD

**Issue by tusharnankani** [Python-World/Python_and_the_Web#51]
# Description
Scrape the S&P 500 Companies list from Wikipedia, Yahoo Finance, etc., then output the data.
Get stock prices

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [X] Feature (New Script)

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by antoniouaa** [comment]
To clarify, what sort of data do you want collected from the companies?

**Comment by tusharnankani** [comment]
> To clarify, what sort of data do you want collected from the companies?

Stock prices, Company name and extra useful information that can be scraped.

**Comment by antoniouaa** [comment]
> Stock prices, Company name and extra useful information that can be scraped.

Just from Wiki or would you want to use other websites for financial data like Yahoo! Finance?

**Comment by tusharnankani** [comment]
> Just from Wiki or would you want to use other websites for financial data like Yahoo! Finance?

Yes, you can use other websites as well!

**Comment by AdityaJ7** [comment]
Due you want to be assigned to this issue @antoniouaa  ?

**Comment by roopbiswas** [comment]
I would like to contribute on this. Let me know if it is okay to take up this issue..

**Comment by AdityaJ7** [comment]
> I would like to contribute on this. Let me know if it is okay to take up this issue..

I guess @antoniouaa  is interested in this issue @roopbiswas he is in a different time zone so he might reply a bit late,  if he is not interested then we will assign this issue to you.

Thanks

**Comment by roopbiswas** [comment]
cool. thanks!

**Comment by antoniouaa** [comment]
Hi, yes i'm interested in this issue and started developing code for it already.

**Comment by AdityaJ7** [comment]
Cool @antoniouaa assigning it to you
