### ISSUE TITLE
Python Script to Download Latest Dilbert Comic 

### ISSUE THREAD

**Issue by ADV1K** [Python-World/Python_and_the_Web#518]
# Description

Python Script to Download Latest Dilbert Comic and open it in your default image viewer program.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by valterm** [comment]
I'd like to work on this, could this please be assigned to me?

**Comment by AdityaJ7** [comment]
> I'd like to work on this, could this please be assigned to me?

sorry the issue's author has already submitted a pr related to it
