### ISSUE TITLE
Turtle Clock

### ISSUE THREAD

**Issue by ADV1K** [Python-World/Python_and_the_Web#521]
## Description

A simple Analog Clock made with Python Turtle

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
@ADV1K  Please don't clear the Issue or PR template from next time

**Comment by krishnasharma1386** [comment]
can I submit my pull request on this topic?

**Comment by AdityaJ7** [comment]
> can I submit my pull request on this topic?

No, this issue has been claimed
