### ISSUE TITLE
PacMan using PyGame

### ISSUE THREAD

**Issue by ritik-malik** [Python-World/Python_and_the_Web#523]
# PacMan using PyGame

A simple implementation of the original PacMan in python using the PyGame library

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by gurleen3** [comment]
Sir, I am a beginner, How can I contribute to the issue?

**Comment by AdityaJ7** [comment]
> Sir, I am a beginner, How can I contribute to the issue?

This issue has been resolved,  we will be posting other issues soon
