### ISSUE TITLE
Mass Mail Spammer

### ISSUE THREAD

**Issue by ritik-malik** [Python-World/Python_and_the_Web#533]
# Mass Mail Spammer

A python + bash script to send any number of trash emails from your google account, with custom trash messages (can also be taken from a file) to any target. The connection is made via secure openssl to GSMTP

## Type of issue

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by tdserapio** [comment]
Although I will be using pyautougui, may I be assigned this task?
