### ISSUE TITLE
Scientific Calculator in Python

### ISSUE THREAD

**Issue by lavish619** [Python-World/Python_and_the_Web#561]
# Description

I want to add a GUI Scientific Calculator script in python.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by kartavyashankar** [comment]
I want to try this
Please assign it to me

**Comment by AdityaJ7** [comment]
> I want to try this
> Please assign it to me

Sorry @kartavyashankar the issue author has already completed this

**Comment by kartavyashankar** [comment]
Oh, Okay :)
