### ISSUE TITLE
Please make only meaningful PRs

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#57]
Unnecessary PRs will be marked as spam and invalid and won't be counted under Hacktoberfest so please refrain from making unnecessary Pull requests.

Thanks

**Comment by tusharnankani** [comment]
Yes! Please stick to [Quality Standards](https://hacktoberfest.digitalocean.com/details#quality), please make meaningful Pull Requests (PR).

**Comment by aniket786333** [comment]
Thanks sir

**Comment by asiskumarroy** [comment]
Thaank you Sir,I would like to contribute by adding a fake news detection web app built in flask and using NLP techniques for detection

**Comment by AdityaJ7** [comment]
> Thank you Sir,I would like to contribute by adding a fake news detection web app built in flask and using NLP techniques for detection

okay

**Comment by AdityaJ7** [comment]
> Thank you Sir,I would like to contribute by adding a fake news detection web app built in flask and using NLP techniques for detection

You can work on it @asiskumarroy

**Comment by xcodz-dot** [comment]
I have a good production ready shopify web scraper (My own work), So i am wanting to CONTRIBUTE her.

**Comment by rishu1722** [comment]
So , i read about it i cam develop abot to contribute in it.

**Comment by dingusagar** [comment]
i have added a python script that searches a text accross different captions files (srt files) and brings up the results in a nice format. The PR can be found here. #262 
please review it and give comments if any. Also consider merging it if there arent any issues.

**Comment by rishu1722** [comment]
But what I have to do sir?make a new script?
