### ISSUE TITLE
Python script to add Youtube video to Spotify playlist

### ISSUE THREAD

**Issue by schezfaz** [Python-World/Python_and_the_Web#589]
# Description
A python script that allows you to add a particular youtube video to a spotify playlist

## Type of issue
- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:
- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by schezfaz** [comment]
I'd like to work on this!

**Comment by aniket173000** [comment]
HEY CAN YOU PLEASE ASSIGN THIS TASK TO ME.

**Comment by AdityaJ7** [comment]
> HEY CAN YOU PLEASE ASSIGN THIS TASK TO ME.

the author of the issue is already working on it

**Comment by schezfaz** [comment]
Hii, apologies for the delay. I have not been able to kickstart work on this script. @aniket173000 can take it ahead if they like!!
