### ISSUE TITLE
Python script to download the top 5 posts from the /r/wallpapers subreddit every day

### ISSUE THREAD

**Issue by valterm** [Python-World/Python_and_the_Web#595]
# Description

A python script, that would download the top 5 posts from the [/r/wallpapers](https://www.reddit.com/r/wallpapers/) subreddit, and save them locally.

## Type of issue

- [X] Feature (New Script)

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by valterm** [comment]
I'd like to work on this please, could it be assigned to me?

**Comment by SaucyGames05** [comment]
I'd like to give this a go

**Comment by valterm** [comment]
I'm working on this already, just haven't had the time to clean the code up yet to be ready for a commit.
