### ISSUE TITLE
Script to scrape cricketer information

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#6]
# Description

Create a script that will take the name of a cricketer as input and will return the information related to him/her like total runs, wickets, strike rate, economy , etc.

## Type of issue

- [x] Feature(New Script)
## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects before submitting a new project issue
- [x] I have checked previous issues to avoid duplicates
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
unassigning due to inactivity!!!

**Comment by varuntumbe** [comment]
Can i try solving this issue ? ( do i have to scrape or can i use an api  )
Thanks in advance

**Comment by AdityaJ7** [comment]
> Can i try solving this issue ? ( do i have to scrape or can i use an api )
> Thanks in advance

Whatever approach suits you @varuntumbe  if you use API than place your folder under API and if you use scraping then place it under web scrappers

Thanks

**Comment by varuntumbe** [comment]
okay sure thanks i will try to do this.

**Comment by varuntumbe** [comment]
Hey wrote a script using scrapping. can you check whether it is correct and what should i  modify?
Thanks in advance.
