### ISSUE TITLE
Python Script to scrape random quotes from Quotes website.

### ISSUE THREAD

**Issue by hrj-star** [Python-World/Python_and_the_Web#600]
# Description

## Type of issue
Will implement a python script to scrape quotes from quotestoscrape website,

- [X] Feature (New Script)
- [X] Get quotes stored in json file

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by VolatianaYuliana** [comment]
Hey @hrj-star I would like to work on this one.

**Comment by hrj-star** [comment]
Hey @VolatianaYuliana , I am already working on this issue . Will complete it as soon as I am assigned to it 😀.
