### ISSUE TITLE
Create a dice roll game with python

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#78]
# Description

Create a simple dice roll game with Python(command-line based)

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Sahil-k1509** [comment]
I would like to work on this. 
Two dices thrown. One with higher number gets point. There will be n rounds(n given as input).
The top of dice would be printed in command line. More points results in win. 
Do you want the name of two players and results of game stored in txt file or anything else?

**Comment by charchithere** [comment]
Hello! I would like to work o this

**Comment by AdityaJ7** [comment]
> Hello! I would like to work o this

Sorry @charchithere it has been assigned to @Sahil-k1509
