### ISSUE TITLE
Basic quiz application with Python 🐍

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#79]
# Description

Create a command-line based quiz application with  🐍

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by xPolar** [comment]
Hey there, I'd be interested in helping with this, do you have any general specifics you'd like to be accomplished?

**Comment by AdityaJ7** [comment]
> Hey there, I'd be interested in helping with this, do you have any general specifics you'd like to be accomplished?

Sure you can go for it.

The script must count the number of correct answers given by the player.
It must have a total of 20 different questions out of which 5 are selected randomly which means scoring must be out of 5 all the time.
If the wrong answer is provided by the user then the current answer must also be displayed.

You can add any type of questions be it Tech/Sports/Politics, etc

**Comment by xPolar** [comment]
Alright, should the answer be displayed after they've finished the quiz or once they've answered the question?

**Comment by AdityaJ7** [comment]
> Alright, should the answer be displayed after they've finished the quiz or once they've answered the question?

Once they've answered it

**Comment by prkhrv** [comment]
I would like to contribute

**Comment by AdityaJ7** [comment]
> I would like to contribute

This issue has been claimed

**Comment by xPolar** [comment]
I can no longer do this, sorry! @prkhrv should be able to take this if they still want to.

**Comment by prkhrv** [comment]
Please assign

**Comment by AdityaJ7** [comment]
> Please assign @AdityaJ7

sure @prkhrv

**Comment by Sahil-k1509** [comment]
hi. I would like to contribute to this in some way or the other. I know it is claimed already. but, @prkhrv  if you need help in creating questions for the quiz. I can help. I created a quizzing website in php so I have 60 questions based on programming and some misc topics. If you would like to check them out, visit my ['Ask me now'](https://github.com/Sahil-k1509/AskMeNow/) repo. questions.php has objects with questions, options, correct answer separated on difficulty levels. :-)

**Comment by prkhrv** [comment]
@Sahil-k1509  Sure !

**Comment by AdityaJ7** [comment]
> hi. I would like to contribute to this in some way or the other. I know it is claimed already. but, @prkhrv if you need help in creating questions for the quiz. I can help. I created a quizzing website in php so I have 60 questions based on programming and some misc topics. If you would like to check them out, visit my ['Ask me now'](https://github.com/Sahil-k1509/AskMeNow/) repo. questions.php has objects with questions, options, correct answer separated on difficulty levels. :-)

You can help if the assigned person is okay with it

**Comment by rishu1722** [comment]
Can i help you out?

**Comment by prkhrv** [comment]
@rishu1722 sure , I will let you know .

**Comment by prkhrv** [comment]
Hi Everyone, I am Done with the quiz but still I have Left Few Little Things , If You Want To contribute just send PRs to this repo
https://github.com/prkhrv/Python-CLI-Quiz , Your PRs will be Counted For HacktoberFest, Please Ask First before Sending PRs.

**Comment by rishu1722** [comment]
Yes I want to do work on this.

**Comment by Sahil-k1509** [comment]
@prkhrv  Sure, I will help in adding more questions

**Comment by prkhrv** [comment]
@AdityaJ7  Added Basic Quiz Application , in PR #480 . Please Review and Merge. 
Thanks a lot every One For the Help .
