### ISSUE TITLE
Scrape all the problems from Project Euler

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#8]
# Description

Write a script to scrape all the problems present in the Project Euler website and store them in a csv or text file.
You can check this [website]( https://projecteuler.net/archives) for reference

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by pratik-choudhari** [comment]
Hey @AdityaJ7 assign me this issue😁

**Comment by AdityaJ7** [comment]
> Hey @AdityaJ7 assign me this issue😁

Sure
