### ISSUE TITLE
Custom Wordlist Generator using Python

### ISSUE THREAD

**Issue by madhavmehndiratta** [Python-World/Python_and_the_Web#80]
# Description
I will be creating a custom wordlist generator which creates a wordlist based on the inputs given by the user. This can be useful in brute force attacks.

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
This script must go under the Miscellaneous Folder

**Comment by tusharnankani** [comment]
Fixed in PR #81
