### ISSUE TITLE
Scrape CodeChef Problem Statement and store it as a text file

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/Python_and_the_Web#9]
# Description

Write a script that takes a problem code, scrapes the concerned problem statement and stores it in a text file

## Type of issue

- [x] Feature (New Script)

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by officialpm** [comment]
#### I would like to solve this !!
