### ISSUE TITLE
Google Search Using Python Script

### ISSUE THREAD

**Issue by nj1902** [Python-World/Python_and_the_Web#90]
# Description
My script will shows google search result. README attached. 
I am adding a script in an attempt to learn more about hacktoberfest.

## Type of issue
- NOTE: *These boxes can be checked using **`[X]`***

- [x] Feature (New Script)
- [ ] Bug
- [x] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
Ok @nj1902  put your script folder inside Miscellaneous
