### ISSUE TITLE
 Twitter bot

### ISSUE THREAD

**Issue by Mysterious-Owl** [Python-World/Python_and_the_Web#93]
# Description

twitter bot to like, retweet your tweet/with specific keyword/hashtag

## Type of issue

- [X] Feature (New Script)

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked all the existing projects, before submitting a new project issue.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by AdityaJ7** [comment]
HI @Mysterious-Owl  we already have a word cloud script you can go ahead with the Twitter bot
and add it to the Bot directory of this project,

Thanks
